In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("qoute_dataset.csv")

In [5]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [6]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [7]:
df.shape

(3038, 2)

In [8]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [9]:
quotes = quotes.str.lower()

In [10]:
import string
translator = str.maketrans('','',string.punctuation)
quotes = quotes.apply(lambda x : x.translate(translator))

In [11]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [13]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [14]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [15]:
sequence = tokenizer.texts_to_sequences(quotes)

In [16]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [17]:
print(sequence[0])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]

In [18]:
X = []
y = []

for seq in sequence:
    for i in range(1,len(seq)):
        input_seq = seq[:i]
        output_seq = seq[i]
        X.append(input_seq)
        y.append(output_seq)

In [19]:
len(X)

85271

In [20]:
len(y)

85271

In [21]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [22]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X,maxlen = max_len,padding = 'pre')

In [23]:
X_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 713], dtype=int32)

In [24]:
y = np.array(y)

In [25]:
X_padded.shape

(85271, 745)

In [26]:
y.shape

(85271,)

In [27]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y,num_classes = vocab_size)

In [28]:
y.shape

(85271,)

In [29]:
y_one_hot.shape

(85271, 10000)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

In [31]:
embedding_dim = 50
rnn_units = 128

In [32]:
rnn_model = Sequential()
rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len)
)

rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [33]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics= ['accuracy']
)

In [34]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
lstm_model = Sequential()

In [36]:
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [37]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics= ['accuracy']
)

In [38]:
epochs =100
batch_size = 128

In [39]:
history_rnn = rnn_model.fit(
    X_padded,y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 94ms/step - accuracy: 0.0457 - loss: 6.7093 - val_accuracy: 0.0595 - val_loss: 6.5376
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.0793 - loss: 6.0822 - val_accuracy: 0.0902 - val_loss: 6.3369
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.1037 - loss: 5.7302 - val_accuracy: 0.1013 - val_loss: 6.3015
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.1195 - loss: 5.4393 - val_accuracy: 0.1057 - val_loss: 6.3410
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.1315 - loss: 5.2015 - val_accuracy: 0.1067 - val_loss: 6.3654
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.1421 - loss: 5.0089 - val_accuracy: 0.1110 - val_loss: 6.3575
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.1563 - loss: 4.7713 - val_accuracy: 0.1103 - val_loss: 6.4326
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.1711 - loss: 4.5746 - val_accuracy: 0.1132 - val_loss: 6.5077
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.1888 - loss: 4.3907 - val_accuracy: 0.1078 - val_loss: 6.5830
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.2093 - loss: 4.2167 - val_accuracy: 0.1068 - val_loss: 6.6543
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.2294 - loss: 4.0507 - val_accuracy: 0.1061 - val_loss: 6.7256
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.2511 - loss: 3.8941 - val_accuracy: 0.1023 - val_loss: 6.8142
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 72ms/step - accuracy: 0.2725 - loss: 3.7482 - val_accuracy: 0.1018 - val_loss: 6.8824
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.2916 - loss: 3.6116 - val_accuracy: 0.0972 - val_loss: 6.9650
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 72ms/step - accuracy: 0.3131 - loss: 3.4860 - val_accuracy: 0.0959 - val_loss: 7.0480
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.3294 - loss: 3.3684 - val_accuracy: 0.0980 - val_loss: 7.1084
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 72ms/step - accuracy: 0.3461 - loss: 3.2595 - val_accuracy: 0.0952 - val_loss: 7.1803
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.3625 - loss: 3.1572 - val_accuracy: 0.0969 - val_loss: 7.2533
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 72ms/step - accuracy: 0.3772 - loss: 3.0619 - val_accuracy: 0.0946 - val_loss: 7.3219
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.3928 - loss: 2.9724 - val_accuracy: 0.0924 - val_loss: 7.3917
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 72ms/step - accuracy: 0.4067 - loss: 2.8879 - val_accuracy: 0.0940 - val_loss: 7.4437
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4204 - loss: 2.8092 - val_accuracy: 0.0868 - val_loss: 7.5240
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4324 - loss: 2.7358 - val_accuracy: 0.0912 - val_loss: 7.5884
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4451 - loss: 2.6664 - val_accuracy: 0.0878 - val_loss: 7.6551
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4567 - loss: 2.5984 - val_accuracy: 0.0844 - val_loss: 7.7154
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4671 - loss: 2.5365 - val_accuracy: 0.0865 - val_loss: 7.7758
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4763 - loss: 2.4870 - val_accuracy: 0.0828 - val_loss: 7.8478
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4737 - loss: 2.4936 - val_accuracy: 0.0871 - val_loss: 7.8949
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.4824 - loss: 2.4472 - val_accuracy: 0.0841 - val_loss: 7.9469
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5007 - loss: 2.3470 - val_accuracy: 0.0841 - val_loss: 8.0100
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5089 - loss: 2.3078 - val_accuracy: 0.0871 - val_loss: 8.0639
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5207 - loss: 2.2387 - val_accuracy: 0.0831 - val_loss: 8.1361
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5256 - loss: 2.2139 - val_accuracy: 0.0824 - val_loss: 8.1898
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5312 - loss: 2.1706 - val_accuracy: 0.0815 - val_loss: 8.2331
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5447 - loss: 2.1093 - val_accuracy: 0.0793 - val_loss: 8.2922
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5496 - loss: 2.0832 - val_accuracy: 0.0760 - val_loss: 8.3444
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5573 - loss: 2.0370 - val_accuracy: 0.0830 - val_loss: 8.4126
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5624 - loss: 2.0072 - val_accuracy: 0.0790 - val_loss: 8.4654
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5711 - loss: 1.9713 - val_accuracy: 0.0787 - val_loss: 8.5133
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5751 - loss: 1.9393 - val_accuracy: 0.0783 - val_loss: 8.5875
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5826 - loss: 1.9081 - val_accuracy: 0.0763 - val_loss: 8.6208
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5865 - loss: 1.8915 - val_accuracy: 0.0767 - val_loss: 8.7087
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5799 - loss: 1.9042 - val_accuracy: 0.0775 - val_loss: 8.7159
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.5780 - loss: 1.9196 - val_accuracy: 0.0753 - val_loss: 8.7806
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6002 - loss: 1.8172 - val_accuracy: 0.0762 - val_loss: 8.8086
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.6096 - loss: 1.7778 - val_accuracy: 0.0749 - val_loss: 8.8832
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6138 - loss: 1.7539 - val_accuracy: 0.0756 - val_loss: 8.8952
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6173 - loss: 1.7318 - val_accuracy: 0.0739 - val_loss: 8.9723
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6209 - loss: 1.7103 - val_accuracy: 0.0776 - val_loss: 9.0249
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.6241 - loss: 1.6929 - val_accuracy: 0.0762 - val_loss: 9.0861
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6288 - loss: 1.6710 - val_accuracy: 0.0715 - val_loss: 9.1237
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.6339 - loss: 1.6464 - val_accuracy: 0.0732 - val_loss: 9.1693
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6362 - loss: 1.6326 - val_accuracy: 0.0727 - val_loss: 9.2264
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6408 - loss: 1.6110 - val_accuracy: 0.0743 - val_loss: 9.2622
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6442 - loss: 1.5909 - val_accuracy: 0.0743 - val_loss: 9.3128
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6480 - loss: 1.5725 - val_accuracy: 0.0755 - val_loss: 9.3707
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6510 - loss: 1.5600 - val_accuracy: 0.0746 - val_loss: 9.4359
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6506 - loss: 1.5572 - val_accuracy: 0.0743 - val_loss: 9.4572
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6568 - loss: 1.5281 - val_accuracy: 0.0740 - val_loss: 9.4953
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6589 - loss: 1.5169 - val_accuracy: 0.0732 - val_loss: 9.5529
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6616 - loss: 1.5015 - val_accuracy: 0.0745 - val_loss: 9.5907
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6650 - loss: 1.4864 - val_accuracy: 0.0718 - val_loss: 9.6548
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6652 - loss: 1.4763 - val_accuracy: 0.0718 - val_loss: 9.6966
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6712 - loss: 1.4533 - val_accuracy: 0.0746 - val_loss: 9.7399
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6729 - loss: 1.4457 - val_accuracy: 0.0747 - val_loss: 9.7563
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6743 - loss: 1.4381 - val_accuracy: 0.0711 - val_loss: 9.8177
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6770 - loss: 1.4231 - val_accuracy: 0.0728 - val_loss: 9.8539
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6804 - loss: 1.4137 - val_accuracy: 0.0726 - val_loss: 9.8911
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6825 - loss: 1.3981 - val_accuracy: 0.0700 - val_loss: 9.9389
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6836 - loss: 1.3863 - val_accuracy: 0.0715 - val_loss: 9.9855
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6270 - loss: 1.6376 - val_accuracy: 0.0720 - val_loss: 9.9662
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.6258 - loss: 1.6239 - val_accuracy: 0.0704 - val_loss: 9.9901
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6497 - loss: 1.5237 - val_accuracy: 0.0702 - val_loss: 10.0129
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6734 - loss: 1.4308 - val_accuracy: 0.0689 - val_loss: 10.0453
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6876 - loss: 1.3684 - val_accuracy: 0.0712 - val_loss: 10.0816
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6983 - loss: 1.3288 - val_accuracy: 0.0691 - val_loss: 10.1263
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6974 - loss: 1.3269 - val_accuracy: 0.0685 - val_loss: 10.1633
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7000 - loss: 1.3170 - val_accuracy: 0.0720 - val_loss: 10.2057
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7003 - loss: 1.3130 - val_accuracy: 0.0735 - val_loss: 10.2669
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7016 - loss: 1.3047 - val_accuracy: 0.0726 - val_loss: 10.2893
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6556 - loss: 1.5025 - val_accuracy: 0.0682 - val_loss: 10.2637
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.6783 - loss: 1.3899 - val_accuracy: 0.0722 - val_loss: 10.3275
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7055 - loss: 1.2808 - val_accuracy: 0.0700 - val_loss: 10.3991
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7114 - loss: 1.2589 - val_accuracy: 0.0707 - val_loss: 10.4190
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7123 - loss: 1.2530 - val_accuracy: 0.0697 - val_loss: 10.4460
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7124 - loss: 1.2522 - val_accuracy: 0.0687 - val_loss: 10.4895
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7113 - loss: 1.2498 - val_accuracy: 0.0714 - val_loss: 10.5377
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7123 - loss: 1.2440 - val_accuracy: 0.0686 - val_loss: 10.5738
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7115 - loss: 1.2501 - val_accuracy: 0.0697 - val_loss: 10.6168
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7125 - loss: 1.2375 - val_accuracy: 0.0692 - val_loss: 10.6727
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7150 - loss: 1.2276 - val_accuracy: 0.0720 - val_loss: 10.6792
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7172 - loss: 1.2211 - val_accuracy: 0.0707 - val_loss: 10.7171
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7171 - loss: 1.2130 - val_accuracy: 0.0728 - val_loss: 10.7519
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7206 - loss: 1.2027 - val_accuracy: 0.0688 - val_loss: 10.7887
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7202 - loss: 1.2025 - val_accuracy: 0.0697 - val_loss: 10.8053
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7099 - loss: 1.2475 - val_accuracy: 0.0698 - val_loss: 10.8312
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.6220 - loss: 1.6260 - val_accuracy: 0.0684 - val_loss: 10.7879
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.7013 - loss: 1.2729 - val_accuracy: 0.0714 - val_loss: 10.8162
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7251 - loss: 1.1864 - val_accuracy: 0.0721 - val_loss: 10.8588
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.7260 - loss: 1.1761 - val_accuracy: 0.0708 - val_loss: 10.8859

In [40]:
history_lstm = lstm_model.fit(
    X_padded,y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 24s 34ms/step - accuracy: 0.0391 - loss: 6.7571 - val_accuracy: 0.0462 - val_loss: 6.6833
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.0585 - loss: 6.3228 - val_accuracy: 0.0629 - val_loss: 6.5658
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.0790 - loss: 6.0582 - val_accuracy: 0.0869 - val_loss: 6.4731
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.0980 - loss: 5.8299 - val_accuracy: 0.0976 - val_loss: 6.4381
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1097 - loss: 5.6421 - val_accuracy: 0.1014 - val_loss: 6.4128
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1190 - loss: 5.4696 - val_accuracy: 0.1062 - val_loss: 6.4204
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1288 - loss: 5.3112 - val_accuracy: 0.1072 - val_loss: 6.4435
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1355 - loss: 5.1645 - val_accuracy: 0.1074 - val_loss: 6.4596
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1426 - loss: 5.0262 - val_accuracy: 0.1092 - val_loss: 6.5025
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1498 - loss: 4.8906 - val_accuracy: 0.1106 - val_loss: 6.5449
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1565 - loss: 4.7616 - val_accuracy: 0.1107 - val_loss: 6.5990
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1645 - loss: 4.6344 - val_accuracy: 0.1119 - val_loss: 6.6610
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1723 - loss: 4.5113 - val_accuracy: 0.1117 - val_loss: 6.7247
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1819 - loss: 4.3898 - val_accuracy: 0.1122 - val_loss: 6.7999
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.1938 - loss: 4.2711 - val_accuracy: 0.1120 - val_loss: 6.8821
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.2072 - loss: 4.1557 - val_accuracy: 0.1121 - val_loss: 6.9362
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.2212 - loss: 4.0446 - val_accuracy: 0.1103 - val_loss: 7.0246
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.2354 - loss: 3.9387 - val_accuracy: 0.1101 - val_loss: 7.0925
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.2500 - loss: 3.8370 - val_accuracy: 0.1105 - val_loss: 7.1925
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.2636 - loss: 3.7425 - val_accuracy: 0.1123 - val_loss: 7.2610
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - accuracy: 0.2770 - loss: 3.6542 - val_accuracy: 0.1094 - val_loss: 7.3364
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - accuracy: 0.2897 - loss: 3.5724 - val_accuracy: 0.1067 - val_loss: 7.4175
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.3005 - loss: 3.4942 - val_accuracy: 0.1100 - val_loss: 7.5120
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.3130 - loss: 3.4206 - val_accuracy: 0.1046 - val_loss: 7.5723
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.3248 - loss: 3.3519 - val_accuracy: 0.1034 - val_loss: 7.6459
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.3335 - loss: 3.2850 - val_accuracy: 0.1052 - val_loss: 7.7256
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.3445 - loss: 3.2215 - val_accuracy: 0.1071 - val_loss: 7.7997
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.3539 - loss: 3.1614 - val_accuracy: 0.1049 - val_loss: 7.8762
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.3640 - loss: 3.1009 - val_accuracy: 0.1034 - val_loss: 7.9400
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.3739 - loss: 3.0453 - val_accuracy: 0.1045 - val_loss: 8.0082
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.3830 - loss: 2.9894 - val_accuracy: 0.1015 - val_loss: 8.0790
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.3915 - loss: 2.9371 - val_accuracy: 0.1011 - val_loss: 8.1488
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.4001 - loss: 2.8867 - val_accuracy: 0.1015 - val_loss: 8.2072
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.4091 - loss: 2.8371 - val_accuracy: 0.1001 - val_loss: 8.2773
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.4174 - loss: 2.7886 - val_accuracy: 0.1007 - val_loss: 8.3253
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.4268 - loss: 2.7417 - val_accuracy: 0.0984 - val_loss: 8.3929
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - accuracy: 0.4338 - loss: 2.6973 - val_accuracy: 0.0958 - val_loss: 8.4619
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.4414 - loss: 2.6523 - val_accuracy: 0.0983 - val_loss: 8.5088
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.4496 - loss: 2.6090 - val_accuracy: 0.0973 - val_loss: 8.5779
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4564 - loss: 2.5671 - val_accuracy: 0.0959 - val_loss: 8.6426
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4653 - loss: 2.5277 - val_accuracy: 0.0951 - val_loss: 8.7125
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4723 - loss: 2.4867 - val_accuracy: 0.0952 - val_loss: 8.7670
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4798 - loss: 2.4479 - val_accuracy: 0.0944 - val_loss: 8.8092
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4865 - loss: 2.4117 - val_accuracy: 0.0906 - val_loss: 8.8786
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4937 - loss: 2.3748 - val_accuracy: 0.0920 - val_loss: 8.9451
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.4996 - loss: 2.3377 - val_accuracy: 0.0916 - val_loss: 8.9911
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5064 - loss: 2.3033 - val_accuracy: 0.0906 - val_loss: 9.0556
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5124 - loss: 2.2709 - val_accuracy: 0.0895 - val_loss: 9.1107
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5205 - loss: 2.2361 - val_accuracy: 0.0884 - val_loss: 9.1713
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5260 - loss: 2.2040 - val_accuracy: 0.0891 - val_loss: 9.2143
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5320 - loss: 2.1721 - val_accuracy: 0.0909 - val_loss: 9.2923
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5381 - loss: 2.1420 - val_accuracy: 0.0867 - val_loss: 9.3515
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5436 - loss: 2.1134 - val_accuracy: 0.0885 - val_loss: 9.3889
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5493 - loss: 2.0828 - val_accuracy: 0.0879 - val_loss: 9.4490
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5559 - loss: 2.0534 - val_accuracy: 0.0898 - val_loss: 9.4983
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5605 - loss: 2.0246 - val_accuracy: 0.0877 - val_loss: 9.5578
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5659 - loss: 1.9985 - val_accuracy: 0.0878 - val_loss: 9.6156
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5715 - loss: 1.9711 - val_accuracy: 0.0881 - val_loss: 9.6436
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5780 - loss: 1.9442 - val_accuracy: 0.0867 - val_loss: 9.7393
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5829 - loss: 1.9195 - val_accuracy: 0.0861 - val_loss: 9.7611
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5884 - loss: 1.8948 - val_accuracy: 0.0875 - val_loss: 9.8056
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5922 - loss: 1.8703 - val_accuracy: 0.0855 - val_loss: 9.8706
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.5977 - loss: 1.8452 - val_accuracy: 0.0858 - val_loss: 9.9251
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.6023 - loss: 1.8219 - val_accuracy: 0.0850 - val_loss: 9.9818
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6075 - loss: 1.7998 - val_accuracy: 0.0828 - val_loss: 10.0242
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6118 - loss: 1.7757 - val_accuracy: 0.0855 - val_loss: 10.0606
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6161 - loss: 1.7548 - val_accuracy: 0.0833 - val_loss: 10.1355
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6214 - loss: 1.7326 - val_accuracy: 0.0838 - val_loss: 10.1770
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6243 - loss: 1.7116 - val_accuracy: 0.0810 - val_loss: 10.2237
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6288 - loss: 1.6902 - val_accuracy: 0.0838 - val_loss: 10.2924
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6337 - loss: 1.6710 - val_accuracy: 0.0815 - val_loss: 10.3272
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6375 - loss: 1.6502 - val_accuracy: 0.0815 - val_loss: 10.3862
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6417 - loss: 1.6306 - val_accuracy: 0.0835 - val_loss: 10.4438
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6444 - loss: 1.6118 - val_accuracy: 0.0830 - val_loss: 10.4809
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6489 - loss: 1.5935 - val_accuracy: 0.0810 - val_loss: 10.5320
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6532 - loss: 1.5739 - val_accuracy: 0.0789 - val_loss: 10.5715
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6571 - loss: 1.5576 - val_accuracy: 0.0810 - val_loss: 10.6436
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6605 - loss: 1.5393 - val_accuracy: 0.0806 - val_loss: 10.6786
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6647 - loss: 1.5221 - val_accuracy: 0.0814 - val_loss: 10.7437
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6685 - loss: 1.5044 - val_accuracy: 0.0783 - val_loss: 10.7791
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6706 - loss: 1.4884 - val_accuracy: 0.0789 - val_loss: 10.8413
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6749 - loss: 1.4718 - val_accuracy: 0.0773 - val_loss: 10.8878
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6775 - loss: 1.4570 - val_accuracy: 0.0792 - val_loss: 10.9296
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6819 - loss: 1.4400 - val_accuracy: 0.0784 - val_loss: 10.9703
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6855 - loss: 1.4240 - val_accuracy: 0.0794 - val_loss: 11.0373
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6887 - loss: 1.4077 - val_accuracy: 0.0792 - val_loss: 11.0871
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6926 - loss: 1.3951 - val_accuracy: 0.0782 - val_loss: 11.1146
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6945 - loss: 1.3794 - val_accuracy: 0.0786 - val_loss: 11.1529
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.6990 - loss: 1.3647 - val_accuracy: 0.0782 - val_loss: 11.2162
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7011 - loss: 1.3518 - val_accuracy: 0.0782 - val_loss: 11.2765
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7031 - loss: 1.3379 - val_accuracy: 0.0759 - val_loss: 11.2989
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7080 - loss: 1.3229 - val_accuracy: 0.0770 - val_loss: 11.3427
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7093 - loss: 1.3101 - val_accuracy: 0.0755 - val_loss: 11.4166
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7122 - loss: 1.2979 - val_accuracy: 0.0767 - val_loss: 11.4355
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7144 - loss: 1.2848 - val_accuracy: 0.0732 - val_loss: 11.4914
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7181 - loss: 1.2711 - val_accuracy: 0.0772 - val_loss: 11.5180
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.7208 - loss: 1.2579 - val_accuracy: 0.0750 - val_loss: 11.5646
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.7248 - loss: 1.2465 - val_accuracy: 0.0760 - val_loss: 11.6276
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 20s 33ms/step - accuracy: 0.7268 - loss: 1.2345 - val_accuracy: 0.0772 - val_loss: 11.6688
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.7300 - loss: 1.2220 - val_accuracy: 0.0762 - val_loss: 11.6896

In [41]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [42]:
rnn_model.save("rnn_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [43]:
index_to_word ={}
for word,index in word_index.items():
  index_to_word[index] = word

In [46]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [49]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()
  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq],maxlen=max_len,padding='pre')
  pred = model.predict(seq,verbose=0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [52]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

implying

In [54]:
def generate_text(model,tokenizer,seed_text,n_words,max_len):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " "+next_word
  return seed_text

In [55]:
seed = "the meaning of life"
generate_text = generate_text(lstm_model,tokenizer,seed,10,max_len)
print(generate_text)

the meaning of life is not in love it is not madness it is

In [56]:
import pickle
with open('tokenizer.pkl','wb') as f:
  pickle.dump(tokenizer,f)

In [57]:
with open("max_len.pkl","wb") as f:
  pickle.dump(max_len,f)